version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12-browsers-legacy
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b0:64:f1:5c:99:1a:07:5b:8e:8c:36:91:50:ec:64:7b"
      - checkout
      - run:
          command: |
            mkdir -p .git
            touch .git/config
            git config --local user.email "github@kiwigrid.com"
            git config --local user.name "Kiwigrid | GitHub"
            # chrome requires this!
            sudo apt install libxss1

      - run:
          name: Add .npmrc file
          command: echo //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN >> .npmrc
          env:
            NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-

      - run:
          name: Install root dependencies
          command: npm clean-install

      - run:
          name: Install dependencies for all packages
          command: npm run clean-install:all

      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules  # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}

      # temporary deactivated - full pipeline should run first!
      #- run:
      #    name: Lint all packages
      #    command: npm run lint:all

      - run:
          name: Build all packages
          command: npm run build:all

      - run:
          name: Test all packages
          command : npm run test:all

      - run:
          name: Run e2e tests for all packages
          command: npm run test:e2e:all

      - when:
          name: Publish packages
          condition:
            equal: [ master, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Publish version
                command: |
                  echo Start publish now because I am in master branch.
                  npm run lerna:publish
      - unless:
          name: No new version
          condition:
            equal: [ master, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Do not publish
                command: |
                  echo Cannot publish now because I am NOT in  master branch.
                  echo I am in branch: << pipeline.git.branch >>

