version: 2.1

jobs:
  Build-Job:
    docker:
      - image: circleci/node:12

    steps:
      - checkout
      - run:
          name: Add .npmrc file
          command: echo //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN >> .npmrc
          env:
            NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - run:
          name: Install root dependencies
          command: npm clean-install

      - run:
          name: Install dependencies for all packages
          command: npm run clean-install:all

      # temporary deactivated - full pipeline should run first!
      #- run:
      #    name: Lint all packages
      #    command: npm run lint:all

      - run:
          name: Build all packages
          command: npm run build:all
  Test-Job:
    docker:
      - image: circleci/node:12-browsers-legacy
    steps:
      - run:
          name: Test all packages
          command : npm run test:all

      - run:
          name: Run e2e tests for all packages
          command: npm run test:e2e:all


  Release-Job:
    docker:
      - image: circleci/node:12
    steps:
      - run:
          name: Publish packages
          command: npm run lerna:version

workflow:
  version: 2
  Make Fun:
    jobs:
      - Build-Job
      - Test-Job:
          requires:
            - Build-Job
      - Release-Job:
          requires:
            - Test-Job
