version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12-browsers-legacy
    steps:
      - checkout
      - run:
          command: |
            git config --local user.email "github@kiwigrid.com"
            git config --local user.name "Kiwigrid | GitHub"

      - run:
          name: Add .npmrc file
          command: echo //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN >> .npmrc
          env:
            NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - run:
          name: Install root dependencies
          command: npm clean-install

      - run:
          name: Install dependencies for all packages
          command: npm run clean-install:all

      # temporary deactivated - full pipeline should run first!
      #- run:
      #    name: Lint all packages
      #    command: npm run lint:all

      - run:
          name: Build all packages
          command: npm run build:all

      - run:
          name: Test all packages
          command : npm run test:all

      - run:
          name: Run e2e tests for all packages
          command: npm run test:e2e:all

      - when:
          name: Publish packages
          condition:
            equal: [ master, << pipeline.git.branch >> ]
          steps:
            - run:
                name: publish version
                command: |
                  echo Start publish now because I am in master branch.
                  npm run lerna:publish
      - unless:
          name: No new version
          condition:
            equal: [ master, << pipeline.git.branch >> ]
          steps:
            - run:
                name: do not publish
                command: |
                  echo Cannot publish now because I am NOT in  master branch.
                  echo I am in branch: << pipeline.git.branch >>

